### ISSUE TITLE
Enum constants with methods cannot be serialised/deserialised properly

### ISSUE THREAD

**Issue by dadepo** [JungleComputing/ipl#6]
The IBIS serialisation mechanism currently cannot handle enums with enum constants that have methods.

This would be serialised:

```
public enum PrimaryColor {
    RED,
    BLUE,
    GREEN
}
```

This would not be serialised

```
public enum PrimaryColor {
    RED {
        public String toStuff(long d)  { return "stuff"; }
    },
    BLUE {
        public String toStuff(long d)  { return "stuff"; }
    },
    GREEN {
        public String toStuff(long d)  { return "stuff"; }
    }
}
```

An example of a real world Enum with the following structure that fails when serialising with IPL/IBIS is `java.util.concurrent.TimeUnit`

To help reproduced I modified the Hello example. You can see the changes in this commit [https://github.com/dadepo/ipl/commit/b38448f5ed131edaea31164c0916e252440f3097](here)

When the Ibis Serialisation is turned on by specifying `PortType.SERIALIZATION_OBJECT_IBIS`, and the hello example run, it fails with the following stack trace:

```
newInstance fails: got exception java.lang.reflect.InvocationTargetException
java.io.IOException: newInstance failed
	at ibis.io.IbisSerializationInputStream.create_uninitialized_object(IbisSerializationInputStream.java:1551)
	at ibis.io.AlternativeTypeInfo$SerializableReader.readObject(AlternativeTypeInfo.java:273)
	at ibis.io.IbisSerializationInputStream.doReadObject(IbisSerializationInputStream.java:1716)
	at ibis.io.IbisSerializationInputStream.readObject(IbisSerializationInputStream.java:1656)
	at ibis.ipl.impl.ReadMessage.readObject(ReadMessage.java:176)
	at ibis.ipl.examples.Hello.server(Hello.java:54)
	at ibis.ipl.examples.Hello.run(Hello.java:88)
	at ibis.ipl.examples.Hello.main(Hello.java:99)
```

Looking deeper, I see the problem can be found in `SunJavaStuff` class. Specifically in this line: https://github.com/JungleComputing/ipl/blob/390bad379f1271a87f05763f67e80534f436e038/io/src/main/java/ibis/io/SunJavaStuff.java#L281

The call to `newInstance.invoke(objectStreamClass, (java.lang.Object[]) null)` fails because an enum does not have the `newInstance` method. 

Ideally this part of the code should not be exercised for enums, as it leads to the `SerializableReader` being used instead of the `EnumReader`.  

I think the reason why the logic that checks if a class is an enum fails is due to the fact that when the enum constant has methods, they are generated as inner classes. 

I confirmed this issue does not arise when the `SERIALIZATION_OBJECT_SUN` capability is used. It is specific to the serialisation implementation of IPL/IBIS.

**Comment by jmaassen** [comment]
After digging through the code for a bit here are my thoughts:

When sending around objects, the `IbisSerializationOutputStream` and `IbisSerializationInputStream` both use a cache of `AlternativeTypeInfo` objects to  remember which classes they have seen and how they should be serialized. 

Enums are a special case in these `AlternativeTypeInfo` object, just like strings. Instead of doing complicated serialization of all the fields, the enum value is just send. For example "RED" in your `PrimaryColor` test class (without the methods). On the receiving side this "RED" is then use to look up the correct singleton object representing this Enum value. 

However, when enum values also have methods, an inner class is generated and used instead. As a result, the object that is provided to `IbisSerializationOutputStream.writeObject` does not have type `PrimaryColor` but type `PrimaryColor$1` which is seen by `AlternativeTypeInfo` as a regular serializable object. This seems to work on the sending side, but not the receiving side.

The fix for this bug could be to do a bit more analysis in the constructor of `AlternativeTypeInfo`, and recognize that `PrimaryColor$1` is a special case of the `PrimaryColor` enum. This would allow us to simply send the value as a string again and reconstruct the enum on the receiving side.

**Comment by jmaassen** [comment]
Maybe the analysis can check if the `clazz` is an innerclass of an enum?

**Comment by jmaassen** [comment]
Yes, this works in the example code!

Thanks a lot!

**Comment by dadepo** [comment]
I could also confirm it works. Thanks!
